version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - INFERENCE_URL=http://inference:8001/infer
    depends_on:
      - inference

  inference:
    build:
      context: ..
      dockerfile: docker/inference.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../models:/models

  interface:
    build:
      context: ..
      dockerfile: docker/interface.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api


volumes:
  models: